### ISSUE TITLE
V-Drum Explorer issue

### ISSUE THREAD

**Issue by rebelsoxuk** [jskeet/DemoCode#100] opened 2020-05-17 17:48 UTC
Hi.
I've just discovered your software and it looks amazing for what it does, but I can't get it to work on my MSI Laptop Win10 machine. 
The Device options to Load All Data/Load Single Kit etc are all greyed out when I start it up. 
I have my module set to Vendor (and rebooted) as the documentation states and the Log file finds all the correct MIDI ports on my machine.
Any ideas/recommendations to get this to work?
I've attached a screenshot of what it looks like.

Regards
bobby demers

![VDrumExplorer](https://user-images.githubusercontent.com/6031722/82155717-dc6a4d00-986e-11ea-85d7-a5ad9b336f54.png)

**Comment by jskeet** [comment] 2020-05-17 17:55
Firstly, thanks for the really clear bug report.

This is effectively a duplicate of #97. The code didn't handle multiple MIDI ports that *could* have Roland modules on, even if there was *actually* only one Roland drum module attached. This was fixed in #98, but I haven't done a release since then.
The workaround until I *do* get round to another release is to disable your other MIDI devices (Steinberg and KeyLab) - by unplugging them, turning them off, or whatever other way you have of disabling them, then start the Explorer.

My "from scratch rewrite" is getting towards feature parity with the "classic" build that you're currently using... but it's probably still a couple of weeks off. (I only really get time to work on this at the weekend.)
I'll see if I can find time to release alpha05 of the classic UI with this fixed - please let me know whether the workaround will work for you in the meantime. If it's a complete pain to do that, I'll prioritize releasing a new version.

**Comment by rebelsoxuk** [comment] 2020-05-17 18:05
Hi Jon
Cheers, thanks for the quick response. I was just looking through the other responses a few minutes ago when I saw #97.

I've just turned off the Keylab and UR44 and I can confirm it's working now..
Looking forward to the next release! :)
When you've done the next release and sorted this, can I share this around the e-drummer groups? I'm sure there will be a lot of TD17/50/27 owners interested in using it!

Regards
bobby

**Comment by jskeet** [comment] 2020-05-17 18:24
@rebelsoxuk: You're absolutely welcome to share it around. It's never likely to receive the "polish" of a true commercial project, but I do hope it'll prove useful to folks.
(Not just for the editing part, but just the simple "sharing kits by email" for example.)

**Comment by rebelsoxuk** [comment] 2020-05-18 08:16
@jskeet Thanks. 
When the next release comes out I'll pass it around on the FB groups :)

The only thing I can think of that is missing from the program is the ability to upload samples directly from it to individual kits/instruments.  I can see that the Record Instruments  option lets the user include the samples that have been added, is it not possible to upload samples to kits/instruments in the same manner? 
I know the SPD-SX software from Roland (and the commercial equivalent https://spd-sx-editor.com/) allow this for that particular module.
And after reading your plans for future updates, can I put a vote towards audio format selection (I assume you mean .wav/.aiff etc) on the Instrument download  :)

Regards

bobby

**Comment by jskeet** [comment] 2020-05-18 08:35
@rebelsoxuk: Unfortunately we don't have direct access to the sample data (along with a very few other things). The way we "get" the samples for the instrument recorder is pretty horrible - we assign that instrument to the kick pedal, play the kick pedal, and record the audio output. Definitely not the same as having access to the raw bytes, and unfortunately one way only.

Feel free to lobby Roland to add that to their MIDI implementation, of course - I'd love to support it properly! I can't see it happening any time soon, unfortunately. (My dream would be for Roland to decide that V-Drum Explorer is a good idea, and take it on themselves...)

In terms of audio formats, I'm limited to what NAudio is able to write out, but I can definitely look into it.

**Comment by jskeet** [comment] 2020-05-24 07:25
I've just released 1.0.0-alpha05 - sorry for the delay! Download it from the releases page: https://github.com/jskeet/DemoCode/releases

**Closed by jskeet** 2020-05-24 07:25 UTC

**Comment by rebelsoxuk** [comment] 2020-05-24 16:30
Excellent. Thanks Jon :)
I've just opened it up with all my MIDI devices turned on and it works great!

Another question....
The drum kit files I've gotten from some of the aftermarket suppliers (Vexpressions, Michael Shack etc) are all in a .tdo format, but V-Drum Explorer saves/opens .vdrum files. 
Is there a way for V-Drum explorer to access the .tdo files directly so I can mix and match kits from different sources? 
If not, is that in the road map at all?

Regards

bobby

**Comment by jskeet** [comment] 2020-05-24 16:39
@rebelsoxuk: I've created a new issue to track that.
